name: Release a new version
on:
  workflow_dispatch:
jobs:
  publish-to-npmjs:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    environment: npmjs:@open-resource-discovery/specification
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          # registry-url is required for releasing packages
          registry-url: "https://registry.npmjs.org"
      # Skipping install since all assets are pre-built already
      # - run: npm install

      - name: Publish package
        # --provenance enables the automatic generation of provenance statements
        # --access public is only hard required for the initial release, but it doesn't hurt having it setup
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create GitHub Release
        uses: open-resource-discovery/github-release@main
